# Generated by Django 3.0.2 on 2020-01-28 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.CharField(default='', max_length=4095)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=31)),
                ('introduction', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isLeader', models.BooleanField(default=False)),
                ('isMember', models.BooleanField(default=False)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belong_to', to='FC17Website.Teams')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=4095)),
                ('time', models.DateField(auto_now_add=True)),
                ('noticeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FC17Website.Notices')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FC17Website.Users')),
            ],
        ),
    ]
