# Generated by Django 3.0.2 on 2020-01-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='information',
            field=models.CharField(default='', max_length=255),
        ),
    ]
