# Generated by Django 3.0.2 on 2020-02-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0002_team_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='score',
        ),
    ]
