# Generated by Django 3.0.2 on 2020-02-05 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0005_ai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai',
            name='teamname',
        ),
        migrations.RemoveField(
            model_name='ai',
            name='userid',
        ),
        migrations.AddField(
            model_name='ai',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FC17Website.User'),
        ),
    ]
