# Generated by Django 3.0.2 on 2020-01-29 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0005_notices_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
