# Generated by Django 3.0.2 on 2020-01-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0006_notices_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notices',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
