# Generated by Django 3.0.2 on 2020-02-06 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0007_auto_20200206_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FC17Website.Team'),
        ),
    ]
