# Generated by Django 3.0.2 on 2020-02-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0008_ai_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='releaseAi',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
