# Generated by Django 3.0.2 on 2020-01-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0009_auto_20200129_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='notice',
            new_name='noticeq',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='userq',
        ),
    ]
