# Generated by Django 3.0.2 on 2020-02-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0009_team_releaseai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='releaseAi',
        ),
        migrations.AddField(
            model_name='team',
            name='releaseAI',
            field=models.FileField(null=True, upload_to='release/'),
        ),
    ]
