# Generated by Django 3.0.2 on 2020-01-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0010_auto_20200129_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='noticeq',
            new_name='notice',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='userq',
            new_name='user',
        ),
    ]
