# Generated by Django 3.0.2 on 2020-02-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0010_auto_20200207_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='scoreDaily',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='releaseAI',
        ),
        migrations.RemoveField(
            model_name='team',
            name='scoreTotal',
        ),
    ]
