# Generated by Django 3.0.2 on 2020-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0011_auto_20200129_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='avatar',
            field=models.FileField(default='/avatars/default.png', upload_to='avatars/'),
        ),
    ]
