# Generated by Django 3.0.2 on 2020-03-02 07:11

import FC17Website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0011_auto_20200207_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=512)),
                ('team_name', models.CharField(max_length=512)),
                ('team_mate1', models.CharField(max_length=512)),
                ('team_mate2', models.CharField(max_length=512)),
                ('team_mate3', models.CharField(max_length=512)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('file', models.FileField(upload_to=FC17Website.models.user_dirpath_test)),
                ('path', models.CharField(max_length=500)),
                ('origin_name', models.CharField(default=models.CharField(max_length=255), max_length=255)),
                ('exact_name', models.CharField(default=models.CharField(default=models.CharField(max_length=255), max_length=255), max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('selected', models.BooleanField(default=False)),
                ('rank_daily', models.IntegerField(default=0)),
                ('rank_overall', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FileInfo',
                'ordering': ['-timestamp'],
            },
        ),
    ]
