# Generated by Django 3.0.2 on 2020-03-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0012_ai_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai_test',
            name='user',
        ),
    ]
