# Generated by Django 3.0.2 on 2020-02-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0012_teams_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='avatar',
        ),
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.FileField(default='/avatars/default.png', upload_to='avatars/'),
        ),
    ]
