# Generated by Django 3.0.2 on 2020-01-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0002_users_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='isLeader',
            new_name='isCaptain',
        ),
        migrations.AlterField(
            model_name='users',
            name='information',
            field=models.CharField(default='', max_length=1023),
        ),
    ]
