# Generated by Django 3.0.2 on 2020-01-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0007_auto_20200129_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='userID',
            new_name='user',
        ),
    ]
