# Generated by Django 3.0.2 on 2020-01-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC17Website', '0008_auto_20200129_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='noticeID',
            new_name='notice',
        ),
    ]
